spring:
  application:
    name: APIGateway-Service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2



        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - StripPrefix=2




        - id: transitions-service
          uri: lb://TRANSITIONS-SERVICE
          predicates:
            - Path=/api/v1/transitions/**
          filters:
            - StripPrefix=2




        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2



        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/v1/loans/**
          filters:
            - StripPrefix=2





        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/v1/cards/**
          filters:
            - StripPrefix=2





        - id: billPay-service
          uri: lb://BILLPAY-SERVICE
          predicates:
            - Path=/api/v1/billPays/**
          filters:
            - StripPrefix=2
